// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpravaVyrobkuaDilu.Database;

#nullable disable

namespace SpravaVyrobkuaDilu.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240808073031_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpravaVyrobkuaDilu.Database.Models.DilModel", b =>
                {
                    b.Property<int>("DilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DilId"));

                    b.Property<decimal>("Cena")
                        .HasPrecision(16, 4)
                        .HasColumnType("decimal(16,4)");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Popis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Upraveno")
                        .HasColumnType("datetime2");

                    b.Property<int>("VyrobekId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Zalozeno")
                        .HasColumnType("datetime2");

                    b.HasKey("DilId");

                    b.HasIndex("VyrobekId");

                    b.ToTable("DilModel", (string)null);
                });

            modelBuilder.Entity("SpravaVyrobkuaDilu.Database.Models.VyrobekModel", b =>
                {
                    b.Property<int>("VyrobekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VyrobekId"));

                    b.Property<decimal>("Cena")
                        .HasPrecision(16, 4)
                        .HasColumnType("decimal(16,4)");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Popis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poznamka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Upraveno")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Zalozeno")
                        .HasColumnType("datetime2");

                    b.HasKey("VyrobekId");

                    b.ToTable("VyrobekModel", (string)null);
                });

            modelBuilder.Entity("SpravaVyrobkuaDilu.Database.Models.DilModel", b =>
                {
                    b.HasOne("SpravaVyrobkuaDilu.Database.Models.VyrobekModel", "Vyrobek")
                        .WithMany("Dily")
                        .HasForeignKey("VyrobekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vyrobek");
                });

            modelBuilder.Entity("SpravaVyrobkuaDilu.Database.Models.VyrobekModel", b =>
                {
                    b.Navigation("Dily");
                });
#pragma warning restore 612, 618
        }
    }
}
